# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy project files
COPY package.json pnpm-lock.yaml tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts
RUN npm run build

# Start the server via stdio
ENTRYPOINT ["node", "dist/index.js"]
