# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install

# Build the project
COPY . .
RUN npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Default environment variable
ENV MAX_HISTORY_SIZE=1000

# Start the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
